package com.maths;

public class Exception_Task {
	// try with single catch
	private static void method0() {
	
		try {
			int a=3/0;
			System.out.println(a);
		} catch (ArithmeticException e) {
			e.printStackTrace();
		}
	}
	
	//multiple try with single catch
	private static void method4() {
		
		try {
			int a=3/0;
			System.out.println(a);
		}
		finally {
			System.out.println("Ignore Exception");
		}
		try {
			int a=3/0;
			System.out.println(a);
			
		} 
		 catch (ArithmeticException e) {
			e.printStackTrace();
		}
	}
	//single try with multiple catch
		private static void method1() {
			try {
				int a=3/0;
				System.out.println(a);
			} catch (ArithmeticException e) {
				e.printStackTrace();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
			finally {
				System.out.println("Ignore Exception");
			}
		}
		
		//without catch
	private static void method2() {
			try {
				int a=3/0;
				System.out.println(a);
			}
			finally {
				System.out.println("Ignore Exception");
			}
			
			
			
		}
	
	//without try
//	private static void method3() {
//		
//			int a=3/0;
//			System.out.println(a);
//			//catch (ArithmeticException e) {
//				e.printStackTrace();
//			} 
//		
//		//finally {
//			System.out.println("Ignore Exception");
//		}
public static void main(String[] args) {
	method0();
	method1();
	method2();
	method4();
	
}
}

